stages:
  - build
  - test
  - integration-test
  - test-release
  - system-test
  - deploy

image: eclipse-temurin:21

default:
  interruptible: true

.gradle-properties: &gradle-properties
  before_script:
    - touch gradle.properties
    - |
      echo "
      databaseName = rexus-db
      databaseUrl = jdbc:postgresql://localhost:5432/
      databaseUsername = server
      databasePassword = server
      databaseSchema = bot
      " >> gradle.properties

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  <<: *gradle-properties
  script:
    - chmod +x gradlew
    - ./gradlew --build-cache webapp:assemble
  needs: []
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - webapp/build
      - .gradle
  artifacts:
    when: on_success
    name: rexus-backend
    paths:
      - webapp/build/libs/*.jar

build-frontend:
  stage: build
  image: node:24-alpine
  script:
    - cd frontend
    - npm ci
    - npm run check
    - npm run build
  needs: []
  dependencies: []
  artifacts:
    when: on_success
    name: rexus-frontend
    paths:
      - frontend/dist/

test:
  stage: test
  <<: *gradle-properties
  script:
    - chmod +x gradlew
    - ./gradlew webapp:test
  needs:
    - build
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - webapp/build
      - .gradle
  artifacts:
    when: always
    reports:
      junit: webapp/build/test-results/**/*.xml

integration-test:
  stage: integration-test
  variables:
    DB_NAME: "rexus-db"
    DB_URL: jdbc:postgresql://db:5432/$DB_NAME?currentSchema=bot
    DB_USERNAME: server
    DB_PASSWORD: server
  services:
    - name: postgres
      alias: db
      variables:
        POSTGRES_DB: $DB_NAME
        POSTGRES_USER: $DB_USERNAME
        POSTGRES_PASSWORD: $DB_PASSWORD
  <<: *gradle-properties
  script:
    - chmod +x gradlew
    - ./gradlew webapp:integrationTest
  needs:
    - build
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - webapp/build
      - .gradle
  artifacts:
    when: always
    reports:
      junit: webapp/build/test-results/**/*.xml

release-test-image:
  stage: test-release
  image: docker
  services:
    - name: docker:dind
      alias: docker
  variables:
    TEST_IMAGE: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_SHORT_SHA
  dependencies:
    - build
    - build-frontend
  needs:
    - build
    - build-frontend
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build --pull --target pre-built -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

system-test:
  stage: system-test
  variables:
    FF_NETWORK_PER_BUILD: 1
    TEST_IMAGE: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_SHORT_SHA
    DB_NAME: "rexus-db"
    DB_URL: jdbc:postgresql://db:5432/$DB_NAME?currentSchema=bot
    DB_USERNAME: server
    DB_PASSWORD: server
  services:
    - name: postgres
      alias: db
      variables:
        POSTGRES_DB: $DB_NAME
        POSTGRES_USER: $DB_USERNAME
        POSTGRES_PASSWORD: $DB_PASSWORD
    - name: $TEST_IMAGE
      alias: application
    - name: selenium/standalone-chrome:latest
      alias: chrome
  needs:
    - release-test-image
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - webapp/build
      - .gradle
  <<: *gradle-properties
  script:
    - chmod +x gradlew
    - ./gradlew testing:test -Dspring.datasource.url=$DB_URL -Drest-assured.base-uri=http://application/ -Dselenide.base-url=http://application:8080/ -Dselenide.remote=http://chrome:4444 -Dselenide.headless=true
  artifacts:
    when: always
    reports:
      junit: testing/build/test-results/**/*.xml
    paths:
      - testing/build/reports/jgiven

deploy-test-report:
  pages: true
  stage: deploy
  inherit:
    default: false
  image: busybox
  needs:
    - system-test
  when: always
  dependencies:
    - system-test
  script:
    - mv testing/build/reports/jgiven/test/html/ public/
  artifacts:
    paths:
      - "public/"

deploy:
  inherit:
    default: false
  stage: deploy
  image: docker
  services:
    - name: docker:dind
      alias: docker
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/rexus
  dependencies:
    - build
    - build-frontend
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker buildx create --name container-builder --driver docker-container --bootstrap --use
  script:
    - docker buildx build --pull --push --platform linux/amd64,linux/arm64 --target pre-built -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:latest .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
