buildscript {
	dependencies {
		classpath('org.flywaydb:flyway-database-postgresql:10.16.0')
	}
}

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.4'
	id 'io.spring.dependency-management' version '1.1.6'
	id "org.jooq.jooq-codegen-gradle" version "3.19.10"
	id "org.flywaydb.flyway" version "10.16.0"
}

group = 'com.nemo'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '21'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-hateoas'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0' // Newer version throws a compilation error

	implementation 'org.openpnp:opencv:4.9.0-0'

	implementation 'org.flywaydb:flyway-core:10.+'
	runtimeOnly 'org.flywaydb:flyway-database-postgresql:10.+'

	implementation 'org.springframework.boot:spring-boot-starter-jooq'

	runtimeOnly 'org.postgresql:postgresql:42.+'
	jooqCodegen 'org.postgresql:postgresql:42.+'
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	tasks.withType(Test).configureEach {
		if (gradle.startParameter.projectDir == null || (project.name == "testing" && !gradle.startParameter.projectDir.name.contains("testing"))) {
			enabled = false
		}
	}
}

testing {
	suites {
		test {
			useJUnitJupiter()
		}

		integrationTest(JvmTestSuite) {
			dependencies {
				implementation project()
			}

			targets {
				all {
					testTask.configure {
						shouldRunAfter(test)
					}
				}
			}
		}
	}
}

sourceSets {
	integrationTest {
		compileClasspath += main.output
		runtimeClasspath += main.output
	}
}

configurations {
	integrationTestImplementation.extendsFrom implementation
	integrationTestRuntimeOnly.extendsFrom runtimeOnly
}

dependencies {
	integrationTestImplementation 'org.springframework.boot:spring-boot-starter-test'
	integrationTestImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test', Test) {
	useJUnitPlatform()
}

processResources {
	filesMatching("**/application.properties") {
		expand(project.properties)
	}
}

jooqCodegen.dependsOn flywayMigrate

jooq {
	configuration {
		jdbc {
			driver = project.properties.databaseDriver
			url = project.properties.databaseUrl
			user = project.properties.databaseUsername
			password = project.properties.databasePassword
		}
		generator {
			database {
				name = "org.jooq.meta.postgres.PostgresDatabase"
				excludes = "flyway_schema_history"
				inputSchema = project.properties.databaseSchema
			}
			target {
				packageName = "org.jooq.generated"
				directory = "src/main/java"
			}
		}
	}
}

flyway {
	url = project.properties.databaseUrl
	user = project.properties.databaseUsername
	password = project.properties.databasePassword
	driver = project.properties.databaseDriver
	schemas = [project.properties.databaseSchema]
}
