services:
  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - hub
    depends_on:
      db:
        condition: service_healthy
        required: true

  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - hub
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
        

volumes:
  db-data:
networks:
  hub:
