spring.application.name=Rexus
spring.application.version=${version}

springdoc.swagger-ui.path=/api

spring.datasource.url = #[DB_URL:${databaseUrl + databaseName + '?currentSchema=' + databaseSchema}]#
spring.datasource.username = #[DB_USERNAME:${databaseUsername}]#
spring.datasource.password = #[DB_PASSWORD:${databasePassword}]#
spring.datasource.driver-class-name = ${databaseDriver}

spring.flyway.locations=classpath:db/migration
