buildscript {
    dependencies {
        classpath('org.flywaydb:flyway-database-postgresql:11.11.2')
    }
}

plugins {
    id "org.jooq.jooq-codegen-gradle" version "3.20.6"
    id "org.flywaydb.flyway" version "11.11.2"
    id "io.freefair.lombok" version "8.14.2"
}

group = 'com.nemo'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-hateoas'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'

    implementation 'org.openpnp:opencv:4.9.0-0'

    implementation 'org.flywaydb:flyway-core:11.+'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql:11.+'

    implementation 'org.springframework.boot:spring-boot-starter-jooq'

    runtimeOnly 'org.postgresql:postgresql:42.+'
    jooqCodegen 'org.postgresql:postgresql:42.+'

    compileOnly 'org.jetbrains:annotations:26.0.2'
}

testing {
    suites {
        test {
            useJUnitJupiter()
        }

        integrationTest(JvmTestSuite) {
            dependencies {
                implementation project()
            }

            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(test)
                    }
                }
            }
        }
    }
}

sourceSets {
    integrationTest {
        compileClasspath += main.output
        runtimeClasspath += main.output
    }
}

configurations {
    integrationTestImplementation.extendsFrom implementation
    integrationTestRuntimeOnly.extendsFrom runtimeOnly
}

dependencies {
    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-test'
    integrationTestImplementation 'org.springframework.security:spring-security-test'
}

jar {
    enabled = false
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

processResources {
    filesMatching([ "**/application.properties", "**/initDB.sql" ]) {

        expand(project.properties)
        filter { String line ->
            // Replace "#[" with "${" and "]#" with "}", to resolve conflicts between Spring and Gradle
            line.replaceAll("#\\[(.*)]#", "\\\${\$1}")
        }
    }
}

jooqCodegen.dependsOn flywayMigrate

jooq {
    configuration {
        jdbc {
            driver = project.properties.databaseDriver
            url = project.properties.databaseUrl + project.properties.databaseName
            user = project.properties.databaseUsername
            password = project.properties.databasePassword
        }
        generator {
            database {
                name = "org.jooq.meta.postgres.PostgresDatabase"
                excludes = "flyway_schema_history"
                inputSchema = project.properties.databaseSchema
            }
            target {
                packageName = "org.jooq.generated"
                directory = "src/main/java"
            }
        }
    }
}

flyway {
    url = project.properties.databaseUrl + project.properties.databaseName
    user = project.properties.databaseUsername
    password = project.properties.databasePassword
    driver = project.properties.databaseDriver
    schemas = [project.properties.databaseSchema]
}
