name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Build
        run: |
          cd frontend
          npm ci
          npm run check
          npm run build

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rexus-frontend
          path: frontend/dist/

  build:
    name: Build Backend
    needs: build-frontend

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: rexus-db
          POSTGRES_USER: server
          POSTGRES_PASSWORD: server
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: rexus-frontend
          path: frontend/dist/

      - name: Move the static frontend files
        run: mkdir webapp/src/main/resources/public && mv frontend/dist/* webapp/src/main/resources/public/

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Project
        run: >
          ./gradlew webapp:build 
          -PdatabaseUrl=jdbc:postgresql://localhost:5432/
          -PdatabaseName=rexus-db
          -PdatabaseUsername=server
          -PdatabasePassword=server 
          -PdatabaseSchema=bot

      - name: Upload webapp artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rexus-backend
          path: webapp/build/libs/*.jar

  system-test:
    name: System Tests
    needs: build

    runs-on: ubuntu-latest

    env:
      DB_URL: jdbc:postgresql://localhost:5432/rexus-db?currentSchema=bot
      DB_USERNAME: server
      DB_PASSWORD: server

    services:
      db:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: rexus-db
          POSTGRES_USER: server
          POSTGRES_PASSWORD: server
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rexus-backend
          path: webapp/build/libs/

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Print chrome version
        run: chrome --version

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Create gradle.properties
        run: |
          touch gradle.properties
          echo "
          databaseName = rexus-db
          databaseUrl = jdbc:postgresql://localhost:5432/
          databaseUsername = server
          databasePassword = server
          databaseSchema = bot
          " >> gradle.properties

      - name: Run the application
        run: java -jar webapp/build/libs/*.jar &

      - name: Wait for the application to start
        run: |
          URL="http://localhost:8080/swagger-ui/index.html"; INTERVAL=2; MAX_RETRIES=10; COUNT=0; \
          until [ "$(curl -s -o /dev/null -w '%{http_code}' "$URL")" -eq 200 ]; do
            COUNT=$((COUNT+1))
            if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
              echo "Service did not become ready after $MAX_RETRIES attempts."
              exit 1
            fi
            echo "Attempt $COUNT/$MAX_RETRIES failed. Retrying in $INTERVAL seconds..."
            sleep "$INTERVAL"
          done; \
          echo "Service is up! Running commands...";

      - name: Run System Tests
        run: |
          ./gradlew testing:test \
            -Dspring.datasource.url=jdbc:postgresql://localhost:5432/rexus-db?currentSchema=bot \
            -Drest-assured.base-uri=http://localhost \
            -Dselenide.base-url=http://localhost:8080/ \
            -Dselenide.headless=true

      - name: Upload System Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-system
          path: testing/build/test-results/**/*.xml

      - name: Upload JGiven Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jgiven-reports
          path: testing/build/reports/jgiven

  deploy-test-report:
    if: always() && github.event_name == 'push' && github.ref == 'refs/heads/master'

    name: Deploy Test Report
    needs: system-test
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download JGiven Reports
        uses: actions/download-artifact@v4
        with:
          name: jgiven-reports
          path: jgiven-reports

      - name: Check if reports exist
        id: check_reports
        run: |
          if [ -d "jgiven-reports/test/html" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Prepare Public Dir
        if: steps.check_reports.outputs.exists == 'true'
        run: |
          mkdir -p public
          cp -r jgiven-reports/test/html/* public/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    name: Deploy
    needs: [ build, build-frontend, system-test ]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rexus-backend
          path: webapp/build/libs/

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Use release tag
            type=ref,event=tag
            # Add short SHA
            type=sha,format=short
            # Add 'latest' only if NOT a prerelease
            type=raw,value=latest,enable=${{ !github.event.release.prerelease }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: pre-built-complete
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
